language: go
sudo: false
go:
  - 1.3
  - 1.4
  - 1.5
  - tip

install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/zenazn/goji
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .